package com.kawaii.meowbah.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFFFFC0CB)
val md_theme_light_onPrimary = Color(0xFF88394A)
val md_theme_light_primaryContainer = Color(0xFFFFE4E1)
val md_theme_light_onPrimaryContainer = Color(0xFF88394A)
val md_theme_light_secondary = Color(0xFFEC4899)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD9E2)
val md_theme_light_onSecondaryContainer = Color(0xFF88394A)
val md_theme_light_tertiary = Color(0xFFF9A8D4)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9F2)
val md_theme_light_onTertiaryContainer = Color(0xFF88394A)
val md_theme_light_error = Color(0xFFB00020)
val md_theme_light_onError = Color.White
val md_theme_light_errorContainer = Color(0xFFFCD8DF)
val md_theme_light_onErrorContainer = Color(0xFFB00020)
val md_theme_light_background = Color(0xFFFFE4E1)
val md_theme_light_onBackground = Color(0xFF88394A)
val md_theme_light_surface = Color(0xFFFFE4E1)
val md_theme_light_onSurface = Color(0xFF88394A)
val md_theme_light_surfaceVariant = Color(0xFFFDE7EA)
val md_theme_light_onSurfaceVariant = Color(0xFF88394A)
val md_theme_light_outline = Color(0xFFF472B6)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFFF472B6)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF88394A)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE4E1)
val md_theme_dark_secondary = Color(0xFFF9A8D4)
val md_theme_dark_onSecondary = Color(0xFF88394A)
val md_theme_dark_secondaryContainer = Color(0xFFB95A7E)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE4E1)
val md_theme_dark_tertiary = Color(0xFFFFC0CB)
val md_theme_dark_onTertiary = Color(0xFF88394A)
val md_theme_dark_tertiaryContainer = Color(0xFFCF859A)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_error = Color(0xFFCF6679)
val md_theme_dark_onError = Color(0xFF141213)
val md_theme_dark_errorContainer = Color(0xFFB00020)
val md_theme_dark_onErrorContainer = Color(0xFFFCD8DF)
val md_theme_dark_background = Color(0xFF3E272E)
val md_theme_dark_onBackground = Color(0xFFFFE4E1)
val md_theme_dark_surface = Color(0xFF3E272E)
val md_theme_dark_onSurface = Color(0xFFFFE4E1)
val md_theme_dark_surfaceVariant = Color(0xFF5A3B44)
val md_theme_dark_onSurfaceVariant = Color(0xFFFFE4E1)
val md_theme_dark_outline = Color(0xFFF9A8D4)
